<a href="https://colab.research.google.com/github/Kuznvd/C-/blob/main/%D0%9A%D1%83%D0%B7%D0%BD%D0%B5%D1%86%D0%BE%D0%B2_%D0%94_%D0%A1_%D0%A0%D0%A22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.3.1 Задание. Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами

In [30]:
import numpy as np
x = np.array([[0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0], [0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0], [0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0], [0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0]])
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.2 Задание. Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange

In [31]:
import numpy as np

A = np.zeros((5,5)) # Матрица 5x5
A += np.arange(5) # Значение в строках от 0 до 4
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 1.3.3 Задание. Создать массив 3x3x3 со случайными значениями

In [32]:
import numpy as np

Z = np.random.random((3,3,3))
print(Z)

[[[0.59998973 0.10969682 0.19720851]
  [0.3456896  0.21036488 0.57434893]
  [0.637497   0.74144631 0.52504127]]

 [[0.29688462 0.19489759 0.52964716]
  [0.69750625 0.82118818 0.32206874]
  [0.0495156  0.16120625 0.27735523]]

 [[0.67362392 0.44861714 0.68957478]
  [0.07555903 0.51649882 0.22638067]
  [0.02254785 0.68485307 0.63795926]]]


### 1.3.4 Задание. Создать матрицу с 0 внутри, и 1 на границах

In [33]:
import numpy as np

b = np.ones((5, 5))
b[1:-1, 1:-1] = 0
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 1.3.5 Задание. Создайте массив и отсортируйте его по убыванию

In [34]:
import numpy as np

arr = np.arange(1, 10)
print(np.sort(arr)[::-1])

[9 8 7 6 5 4 3 2 1]


### 1.3.6 Задание. Создайте матрицу, выведите ее форму, размер и размерность

In [35]:
import numpy 

a=[[1,5,6,8],[1,2,5,9],[7,5,6,2]]
len(a)
len(a[0])
numpy.shape(a)

(3, 4)

### 2.3.1 Задача. Найдитн евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [36]:
import numpy as np
a = np.array((3, 0, 3))
b = np.array((3, 3, 3))

square = np.square(a - b)
sum_square = np.sum(square)

distance = np.sqrt(sum_square)
print(distance)

3.0


### 2.3.2 Задача. Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных

In [37]:
import pandas as pd
import requests

url='https://raw.githubusercontent.com/akmand/datasets/main/anneal.csv' # Создать URL-адрес
dataframe=pd.read_csv(url) # Загрузить данные

dataframe.head(7)

family product-type steel  carbon  hardness temper_rolling condition  \
0      ?            C     A       8         0              ?         S   
1      ?            C     R       0         0              ?         S   
2      ?            C     R       0         0              ?         S   
3      ?            C     A       0        60              T         ?   
4      ?            C     A       0        60              T         ?   
5      ?            C     A       0        45              ?         S   
6      ?            C     R       0         0              ?         S   

  formability  strength non-ageing  ...  s  p  shape  thick   width   len oil  \
0           ?         0          ?  ...  ?  ?   COIL  0.700   610.0     0   ?   
1           2         0          ?  ...  ?  ?   COIL  3.200   610.0     0   ?   
2           2         0          ?  ...  ?  ?  SHEET  0.700  1300.0   762   ?   
3           ?         0          ?  ...  ?  ?   COIL  2.801   385.1     0   ?   
4           ?         0          ?  ...  ?  ?  SHEET  0.801   255.0   269   ?   
5           ?         0          ?  ...  ?  ?   COIL  1.600   610.0     0   ?   
6           2         0          ?  ...  ?  ?  SHEET  0.699   610.0  4880   Y   

  bore packing class  
0    0       ?     3  
1    0       ?     3  
2    0       ?     3  
3    0       ?     3  
4    0       ?     3  
5    0       ?     3  
6    0       ?     3  

[7 rows x 39 columns]

### 2.3.3 Задача. Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [38]:
import pandas as pd
import requests

url='https://raw.githubusercontent.com/akmand/datasets/main/anneal.csv'

dataframe=pd.read_csv(url)
dataframe.head(10) # первые 10 строк
dataframe.tail(3) # последние 3 строки
dataframe.shape # кол-во строк и столбцов
dataframe.describe() # описательная статистика для любых числовых столбцов
dataframe.iloc[1:4] # для выбора 1 или нескольких строк, либо значений
dataframe[dataframe['steel'] == 'A'].head(5) # новый фрейм из условия

family product-type steel  carbon  hardness temper_rolling condition  \
0      ?            C     A       8         0              ?         S   
3      ?            C     A       0        60              T         ?   
4      ?            C     A       0        60              T         ?   
5      ?            C     A       0        45              ?         S   
7      ?            C     A       0         0              ?         S   

  formability  strength non-ageing  ...  s  p  shape  thick  width  len oil  \
0           ?         0          ?  ...  ?  ?   COIL  0.700  610.0    0   ?   
3           ?         0          ?  ...  ?  ?   COIL  2.801  385.1    0   ?   
4           ?         0          ?  ...  ?  ?  SHEET  0.801  255.0  269   ?   
5           ?         0          ?  ...  ?  ?   COIL  1.600  610.0    0   ?   
7           2         0          ?  ...  ?  ?   COIL  3.300  152.0    0   ?   

  bore packing class  
0    0       ?     3  
3    0       ?     3  
4    0       ?     3  
5    0       ?     3  
7    0       ?     3  

[5 rows x 39 columns]

### 3.3.2 Задание. Загрузить фрейм данных по ссылке. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [39]:
import pandas as pd
import requests
from sklearn.datasets import load_iris

url='https://raw.githubusercontent.com/akmand/datasets/main/anneal.csv' 
dataframe=pd.read_csv(url)

iris = load_iris()
print(iris.data)
print(iris.target)

dataframe.head(7)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

family product-type steel  carbon  hardness temper_rolling condition  \
0      ?            C     A       8         0              ?         S   
1      ?            C     R       0         0              ?         S   
2      ?            C     R       0         0              ?         S   
3      ?            C     A       0        60              T         ?   
4      ?            C     A       0        60              T         ?   
5      ?            C     A       0        45              ?         S   
6      ?            C     R       0         0              ?         S   

  formability  strength non-ageing  ...  s  p  shape  thick   width   len oil  \
0           ?         0          ?  ...  ?  ?   COIL  0.700   610.0     0   ?   
1           2         0          ?  ...  ?  ?   COIL  3.200   610.0     0   ?   
2           2         0          ?  ...  ?  ?  SHEET  0.700  1300.0   762   ?   
3           ?         0          ?  ...  ?  ?   COIL  2.801   385.1     0   ?   
4           ?         0          ?  ...  ?  ?  SHEET  0.801   255.0   269   ?   
5           ?         0          ?  ...  ?  ?   COIL  1.600   610.0     0   ?   
6           2         0          ?  ...  ?  ?  SHEET  0.699   610.0  4880   Y   

  bore packing class  
0    0       ?     3  
1    0       ?     3  
2    0       ?     3  
3    0       ?     3  
4    0       ?     3  
5    0       ?     3  
6    0       ?     3  

[7 rows x 39 columns]